### PR TITLE
Auto hide log panel after transferring

### PR DESCRIPTION
**Pull request by leobasilio**
Hi. This should close issues #253 and #229.

### CODE REVIEW

**Comment by dragonxlwang** [comment]
+1 for this feature! And is it easy to set in config the maximum number of lines in console? It takes too much space after a few upload

**Comment by leobasilio** [comment]
Hi. It's possible to set a maximum height in pixels, not line numbers. Would that be enough? I like collapsing the panel and seeing only the last message. Maybe we could have a "Compact Log Panel" option instead of limiting it's height.

**Comment by dragonxlwang** [comment]
@leobasilio Thanks! That should work for me till the auto hide added! Can you let me know how to set that up?

**Comment by leobasilio** [comment]
You just need to click on the icon in the middle. It will collapse the log panel.

logpanel

**Comment by dragonxlwang** [comment]
Can I set it as a default behavior in package settings?

**Comment by leobasilio** [comment]
Not yet. That's what I meant by a "Compact Log Panel" setting. Maybe we could add this.

**Comment by dragonxlwang** [comment]
Thanks! :+1:

**Pull request merged**
