### PR TITLE
Remote file delete

### PR DESCRIPTION
**Pull request by tamcap**
I do not think this should be merged in just yet - but I would like to use it as a conversation starter. Is this something that belongs in this package? Is the proposed form acceptable?

If yes, I will add remote folder delete to this PR too.

### CODE REVIEW

**Comment by yongkangchen** [comment]
Yes, it belongs in this package, see #39
It would be great of your contributes

**Comment by tamcap** [comment]
OK. I will add remote folder delete and clean up the queue to the new commit.

**Comment by neu-rah** [comment]
Please add rename sync also

**Comment by tamcap** [comment]
I am determined to make it happen, but this PR probably is just the beginning as more remote tools are needed. I will notify you with a new PR.

**Pull request closed without merging**
