### PR TITLE
Adding watched files support

### PR DESCRIPTION
**Pull request by theproducer**
Sometimes its necessary to deal with the result of preprocessors during development.  These changes allow one to have remote-sync watch files for external changes (for example, from sass compliers, babel, etc) and upload them automatically.

### CODE REVIEW

**Comment by stilliard** [comment]
Hey, this looks awesome, any news? :)

**Comment by robsonsobral** [comment]
Thanks you so much, @theproducer !

**Comment by yongkangchen** [comment]
`This branch has conflicts that must be resolved`

**Comment by SebastianTroc** [comment]
Hi guys, I'm very excited to this feature and really hope for a new release of remote-sync with that request merged :)

**Comment by ejurgelionis** [comment]
Thanks, @theproducer! Hope this feature is out soon.

**Comment by robsonsobral** [comment]
@theproducer needs to fix the conflicts first, @ejurgelionis .

**Comment by ejurgelionis** [comment]
@robsonsobral, yep, I know. That was more like a ping to @theproducer. Actually, this feature is the first I missed when I had started to use Atom.

**Comment by enoversum** [comment]
@theproducer Can we help you in any way to get you fix conflicts for a pull?

**Comment by elistone** [comment]
This feature has now been implemented see #261 for more details.

**Pull request closed without merging**
